---
title: "Preliminary_data"
author: "Astrid L."
date: "12/11/2018"
output: html_document
---

#Setting wd, and loading data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

getwd()
locpath= getwd()
setwd(locpath)

library(pacman)
#p_load(ggplot2, rethinking, readxl, brms, metafor, tidyverse, lme4, Rstan)
p_load(ggplot2, tidyverse, lme4, dplyr, lmerTest, data.table, dtplyr, effects, MuMin)


files <- list.files(path = "~/Desktop/Bachelor/BA_EXP/W3 - imit_inhib/data/",pattern = ".csv")
setwd("~/Desktop/Bachelor/BA_EXP/W3 - imit_inhib/data/")
temp <- lapply(files, fread, sep=",")
all_ii <- rbindlist( temp )

#d = read.csv("~/Desktop/Bachelor/BA_EXP/W3 - imit_inhib/data/II_1.csv")
d_IRI = read.csv("~/Desktop/Bachelor/BA_EXP/IRI_data/data-9/data.csv", header = TRUE, row.names=NULL)

```

Cleaning out irrelevant columns
```{r}
colnames(d_IRI) <- colnames(d_IRI[2:38])

d_IRI <- subset(d_IRI, select=c("ID.1", "score_FS.1", "score_EC.1","score_PT.1", "score_PD.1"))
#str(d_IRI)
# I lost one participant data file, but I had manually written down the results. Now I want to add them. I want to replace the wrong data from participant 1 with the right data. Therefore I will first delete the row with ID no. 1's and then add the correct data. 
# first I remove the wrong data for participant 1
d_IRI <- d_IRI[!(d_IRI$ID.1 =="1"),]
# then I add the correct data for participant 1
d_IRI <- rbind(d_IRI, c(1,23, 22, 23, 11))
# the rownumbers seems wrong so to make sure it doesn't give me problems I will make a new df with the variables
d_IRI <- data.frame(d_IRI$ID.1, d_IRI$score_FS.1, d_IRI$score_EC.1, d_IRI$score_PT.1, d_IRI$score_PD.1)

```


#Adding RME score to IRI data
```{r}
# first I have to order the data by ID to make it fit with the column/values I want to add
d_IRI <- d_IRI[order(d_IRI$d_IRI.ID.1),]
# making a new variable in IRI data and assigning a string of values to it
d_IRI$SS <- c(29, 33, 31, 25, 33, 27, 27, 29, 25, 27, 32, 27, 30, 28, 31)

```

# Merge the two datasets 

```{r}
names(d_IRI)[names(d_IRI) == "d_IRI.ID.1"] <- "Participant"
names(d_IRI)[names(d_IRI) == "d_IRI.score_FS.1"] <- "FS"
names(d_IRI)[names(d_IRI) == "d_IRI.score_EC.1"] <- "EC"
names(d_IRI)[names(d_IRI) == "d_IRI.score_PT.1"] <- "PT"
names(d_IRI)[names(d_IRI) == "d_IRI.score_PD.1"] <- "PD"


setwd("~/Desktop/Bachelor/BA_EXP/")
write.csv(d_IRI, file = "d_IRI.csv", row.names=FALSE)

#d <- merge(all_ii,d_IRI,by="Participant")

```


# NOW: STUFF THAT I AM NOT SO SURE ABOUT
```{r}
# should I remove negative RTs
#d$Reaction_time[d$Reaction_time < 0] = 'nan'

# maybe turn my variables into factors???
# turning variables into factors
#str(all_ii)
all_ii$Participant <-factor(all_ii$Participant) #change variable into factor
all_ii$Congruity <-factor(all_ii$Congruity) #change variable into factor
all_ii$Response <-factor(all_ii$Response) #change variable into factor
all_ii$Cue <-factor(all_ii$Cue) #change variable into factor
all_ii$Finger <-factor(all_ii$Finger) #change variable into factor

# checking responses (WHAT DOES THIS MEAN???)
for (p in unique(all_ii$Participant)){
  if (sum(all_ii$Correctness[all_ii$Participant == p]) < 50){
    all_ii$Correctness[all_ii$Correctness==1 & all_ii$Participant == p]=0
    all_ii$Correctness[all_ii$Correctness==0 & all_ii$Participant == p]=1
  }
}

write.csv(all_ii, file = "all_ii_new.csv", row.names=FALSE)

all_ii$Correctness_fac <-factor(all_ii$Correctness) #change variable into factor


```

```{r}

#check RT
rt = ggplot(all_ii,aes(Reaction_time))+geom_density()
print(rt)
#log transform
all_ii$RTlog=log(all_ii$Reaction_time)
rtlog = ggplot(all_ii,aes(RTlog))+geom_density()
print(rtlog)



#group by correctness (finger/congruity)
all_correctness = all_ii %>%
  group_by(Participant, Congruity, Cue) %>%
  summarise(Number_correct=sum(Correctness))


```

```{r}
# building models
m_1 = glmer(Number_correct~Congruity+(1+Congruity|Participant)+(1+Congruity|Cue),family=poisson,all_correctness)
#model1=glmer(Number_correct~Congruity+(1|Participant)+(1|Order_number),family=poisson,all_correctness)
summary(m_1)

model1_2 = glmer(Correctness_fac~Congruity+(1+Congruity|Participant)+(1+Congruity|Cue),family =binomial,all_ii)
print('results for the effect on accuracy')
summary(model1_2)
# summary(model1)

model2=lmer(Reaction_time~Congruity+(1+Congruity|Participant)+(1+Congruity|Cue),all_ii,REML=F)
# print('results for the effect on reaction_time')
summary(model2)

all_ii$V2=all_ii$V1^2
all_ii$V1_scaled=scale(all_ii$V1)
all_ii$V2_scaled=scale(all_ii$V2)
all_ii=subset(all_ii,Reaction_time>0.15)
model3=lmer(Reaction_time~Congruity+V1_scaled+(1+Congruity+Cue|Participant)+(1+Congruity|Cue),all_ii,REML=F)
print('results for the effect on reaction_time (log)')
summary(model3)
simulationOutput <- simulateResiduals(fittedModel = model3, n = 250)

boxplot(RTlog ~ Congruity, main="results for the effect on reaction_time (log)",all_ii)

boxplot(Reaction_time ~ Congruity, main="results for the effect on reaction_time",all_ii)
```







# OKOKAOKOKOKOKAY AND NOW: DIFFERENT STUFF

```{r}
setwd("~/Desktop/Bachelor/BA_EXP/")
d_IRI <- read.csv("~/Desktop/Bachelor/BA_EXP/d_IRI.csv")
d_all_ii <- read.csv("~/Desktop/Bachelor/BA_EXP/all_ii_new.csv", header = TRUE) 

d <- merge(d_all_ii,d_IRI,by="Participant")

# should I remove negative reaction times? 
# should I what
d$Correctness = as.factor(d$Correctness)
d$Participant = as.factor(d$Participant)
d$Correctness = as.factor(d$Correctness)
as.numeric(as.factor(d$Correctness))
d$SS = as.numeric(d$SS)
str(d)
o = lmer(Condition ~ SS + (1|Participant), d)
m = lm(Condition ~ 1 + FS + EC + PT + PD + SS, data = d)
summary(m)
m9 = lmer(Condition ~ 1 + FS + EC + PT + PD + SS + (1 + V1|Participant), data = d)
summary(m9)
```

